export const CHANNEL_HELP_PROTOCOLS = [
  { value: 'modbus-tcp', label: 'Modbus TCP' },
  { value: 'modbus-rtu-over-tcp', label: 'Modbus RTU Over TCP' },
  { value: 'modbus-rtu', label: 'Modbus RTU' },
  { value: 'bacnet-ip', label: 'BACnet IP' },
  { value: 'opc-ua', label: 'OPC UA' },
  { value: 's7', label: 'S7' },
  { value: 'dlt645', label: 'DLT645' },
  { value: 'ethernet-ip', label: 'EtherNet/IP' },
  { value: 'omron-fins', label: 'Omron FINS' },
  { value: 'mitsubishi-slmp', label: 'Mitsubishi MC' },
  { value: 'iec60870-5-104', label: 'IEC 60870-5-104' },
  { value: 'snmp', label: 'SNMP' },
  { value: 'knxnet-ip', label: 'KNXnet/IP' },
]
