# 站点配置
name: EdgeX 文档
description: EdgeX 项目文档网站

# 主题设置
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme  # 添加远程主题支持

# 导航配置
nav:
  - title: 首页
    url: /
  - title: API 文档
    url: /API/API_Index.html
  - title: 手册
    url: /man/USER_MANUAL.html
  - title: 架构
    url: /ARCHITECTURE_V2.html

# 页面配置
permalink: /:path/:basename.html
